#OBS: este projeto não esta com as configurações de Bancos de dados postgres no settings, mude antes para rodar o docker: Ass: Joaquim Lima
services:

    sge_web:
      build: .
      restart: always
      ports: 
        - 8000:8000
      depends_on:
        - sge_db
  
    sge_db:
        image: postgres:15
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=sge

volumes:
    postgres_data: